### ISSUE TITLE
Password does not unlock 

### ISSUE THREAD

**Issue by cryptochainer** [jdogresorg/freewallet-desktop#171]
1. Installed new version
2. Attempt to send
3. Asks me to create password 
4. Enter same p/w twice
5. Unlock wallet
6. Enter password
7. Says is unlocked
8. Attempt to send
9. Says unlock wallet
10. Unlock wallet, enter p/w
11. Lock still locked
12. Attempt to change auto lock time to never
13. Says needs to be unlocked to do so
14. Unlock, enter p/w
15. Go to step 7
16. Install old version from May
17. Asks for p/w
18. Install new version
19. Same behavior

**Comment by snowkidind** [comment]
+1

**Comment by PorkChop77** [comment]
Same Same +2

**Comment by cryptochainer** [comment]
Started again, with a fresh install, and the password function works as expected.

The way I manage my wallets, is with multiple data folders, which are renamed to "Freewallet" as needed.  They are otherwise named "Freewallet-thisotherwallet" or something similar.  Whether or not this is "supported," I have found this to be a pleasing, and effective way to manage differing sets of addresses, used for different purposes.

I was able to restore a backup of the data folder, which lives in ~/Library/Application Support on the Mac.  This time, I elected to "lock" the wallet before doing anything else, which prompted for password creation.  After whence, I unlocked it with said password, and it was indeed unlocked.

Subsequently, I changed the auto-lock to never, and we shall see if it does indeed stay unlocked past the 15 minute mark.

It did stay unlocked.

I revisited the original, unencrypted wallet again. After some use, it became "locked" itself (likely due to the default 15 minute interval).  It prompted me to enter the new password, which I did not.  I changed the auto-lock to "never," and restarted the application.  We will see if it again prompts me to add a password...

**Comment by jdogresorg** [comment]
thank you for this info, I will dig into this issue today and see if I can get it resolved... if you dont want to set a password on your wallet, you should not be forced to, nor should you be locked out of your wallet after setting a password.

**Comment by i3inary** [comment]
i blame this bug for me missing my second bladeepepe.

**Comment by jdogresorg** [comment]
fixed in 0.9.25 release 

https://github.com/jdogresorg/freewallet-desktop/releases/tag/v0.9.25

**Comment by snowkidind** [comment]
This is still broken on my machine after upgrading to 0.9.25 Ventura 13.3.1

**Comment by jdogresorg** [comment]
@snowkidind Do a full reset on your wallet... click logout, confirm to remove all data, then close the app.... reopen freewallet and re-enter your 12-word passphrase.
